version: "3"

services:
  app:
    build: .
    image: surfjudge-pyramid
    restart: unless-stopped
    volumes:
      - ./app/surfjudge:/app/surfjudge
      - ./app/data:/app/data
    environment:
      - WEBSOCKET_URL=wss://websocket.$DOMAIN
      - ZEROMQ_PORT=6545
      - ZEROMQ_HOST=websockets
    networks:
      - traefik
      - default


  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx_traefik.conf:/etc/nginx/nginx.conf:ro
      - ./app/surfjudge/static:/surfjudge/static:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.surfjudge.rule=Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)"
      - "traefik.http.routers.surfjudge.tls.certresolver=le"
      - "traefik.http.routers.surfjudge.entrypoints=websecure"
      - "traefik.http.routers.surfjudge.middlewares=redirecttowww@docker"
      - "traefik.http.middlewares.redirecttowww.redirectregex.regex=^https://${DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirecttowww.redirectregex.replacement=https://www.${DOMAIN}/$${1}"
    networks:
      - traefik
      - default

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=surfjudge2000
    volumes:
      - pgdata:/var/lib/postgresql/data

  websockets:
    image: surfjudge-pyramid
    restart: unless-stopped
    volumes:
      - ./app/surfjudge:/app/surfjudge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.websockets.rule=Host(`websocket.${DOMAIN}`)"
      - "traefik.http.routers.websockets.entrypoints=websecure"
      - "traefik.http.routers.websockets.tls.certresolver=le"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.websockets.middlewares=sslheader@docker"
        #- "traefik.http.services.websockets.loadbalancer.sticky.cookie=true"
    command: python3 /app/surfjudge/websocket_server.py --websocket-port 80 --zeromq-port 6545
    networks:
      - traefik
      - default

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dario.goetz@googlemail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    networks:
      - traefik

volumes:
  pgdata:
networks:
  traefik:
    external: true
