version: "2"

services:
  app:
    build: .
    image: surfjudge-pyramid
    restart: unless-stopped
#    ports:
#     - "2222:80"  # webserver (development version runs on 6543)
#     - "6544:6544"  # websocket server
    volumes:
      - ./app/surfjudge:/app/surfjudge
      - ./app/data:/app/data
    networks:
#      - nginx_default
      - default
    environment:
      # setting "null" as websocket url leads to the frontend trying
      # to puzzle the websocket url from the hostname by adding /websocket
      # which corresponds to the configuration within the surfjudge-nginx
#      - WEBSOCKET_URL=wss://surfjudge.pidario.nsupdate.info/websocket
       - WEBSOCKET_URL=null
       - ZEROMQ_PORT=6545
       - ZEROMQ_HOST=websockets

    # the following command starts the development version
#    command: pserve development.ini

  nginx:
    image: nginx
    restart: unless-stopped
    # only open the following ports in case this service is the main entrypoint
    # on the server, in particular not in a docker-gen (jwilder) setup
    ports:
        - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/surfjudge/static:/surfjudge/static:ro
    # the following environment variables are to be set in
    # the setting of a docker-gen (jwilder) setup
#    environment:
#      - VIRTUAL_HOST=surfjudge.pidario.nsupdate.info
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=surfjudge.pidario.nsupdate.info
#      - LETSENCRYPT_EMAIL=dario.goetz@googlemail.com
    networks:
#      - nginx_default
      - default

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=surfjudge2000
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  websockets:
    image: surfjudge-pyramid
    restart: unless-stopped
    volumes:
      - ./app/surfjudge:/app/surfjudge
    command: python3 /app/surfjudge/websocket_server.py --websocket-port 6544 --zeromq-port 6545

volumes:
  pgdata:
#networks:
#  nginx_default:
#    external: true
